// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pismolet.Web.Infrastructure.Postmaster;

#nullable disable

namespace Pismolet.Infrastructure.Migrations.Postmaster
{
    [DbContext(typeof(MailruPostmasterDbContext))]
    [Migration("20260709201409_InitialMailruPostmasterStorage")]
    partial class InitialMailruPostmasterStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterDomainDailyMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Complaints")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("DeletedRead")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedUnread")
                        .HasColumnType("bigint");

                    b.Property<long>("Delivered")
                        .HasColumnType("bigint");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<long>("MessagesSent")
                        .HasColumnType("bigint");

                    b.Property<long>("ProbablySpam")
                        .HasColumnType("bigint");

                    b.Property<double>("ProbablySpamPercent")
                        .HasColumnType("double precision");

                    b.Property<long>("Read")
                        .HasColumnType("bigint");

                    b.Property<double>("Reputation")
                        .HasColumnType("double precision");

                    b.Property<long>("Spam")
                        .HasColumnType("bigint");

                    b.Property<double>("SpamPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Trend")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Domain", "Date")
                        .IsUnique();

                    b.ToTable("mailru_postmaster_domain_daily_metrics", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterSyncStateEntity", b =>
                {
                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LastDomainDate")
                        .HasColumnType("date");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastMailingSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Domain");

                    b.ToTable("mailru_postmaster_sync_states", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterTroubleSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "Code")
                        .IsUnique();

                    b.HasIndex("Domain", "IsActive");

                    b.ToTable("mailru_postmaster_trouble_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
