// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pismolet.Web.Infrastructure.Postmaster;

#nullable disable

namespace Pismolet.Infrastructure.Migrations.Postmaster
{
    [DbContext(typeof(MailruPostmasterDbContext))]
    [Migration("20260711202750_AddMailruPostmasterAlertJournal")]
    partial class AddMailruPostmasterAlertJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterAlertEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MessagesSent")
                        .HasColumnType("bigint");

                    b.Property<double>("ObservedValue")
                        .HasColumnType("double precision");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "Code", "Fingerprint")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'active'");

                    b.HasIndex("Domain", "Severity", "UpdatedAt");

                    b.HasIndex("Domain", "Status", "UpdatedAt");

                    b.ToTable("mailru_postmaster_alert_events", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterDomainDailyMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Complaints")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("DeletedRead")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedUnread")
                        .HasColumnType("bigint");

                    b.Property<long>("Delivered")
                        .HasColumnType("bigint");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<long>("MessagesSent")
                        .HasColumnType("bigint");

                    b.Property<long>("ProbablySpam")
                        .HasColumnType("bigint");

                    b.Property<double>("ProbablySpamPercent")
                        .HasColumnType("double precision");

                    b.Property<long>("Read")
                        .HasColumnType("bigint");

                    b.Property<double>("Reputation")
                        .HasColumnType("double precision");

                    b.Property<long>("Spam")
                        .HasColumnType("bigint");

                    b.Property<double>("SpamPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Trend")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Domain", "Date")
                        .IsUnique();

                    b.ToTable("mailru_postmaster_domain_daily_metrics", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterMailingDailyMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Complaints")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("DeletedRead")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedUnread")
                        .HasColumnType("bigint");

                    b.Property<long>("Delivered")
                        .HasColumnType("bigint");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<Guid>("MailingId")
                        .HasColumnType("uuid");

                    b.Property<long>("MessagesSent")
                        .HasColumnType("bigint");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("ProbablySpam")
                        .HasColumnType("bigint");

                    b.Property<double>("ProbablySpamPercent")
                        .HasColumnType("double precision");

                    b.Property<long>("Read")
                        .HasColumnType("bigint");

                    b.Property<double>("Reputation")
                        .HasColumnType("double precision");

                    b.Property<long>("Spam")
                        .HasColumnType("bigint");

                    b.Property<double>("SpamPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Trend")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MsgType");

                    b.HasIndex("MailingId", "Date");

                    b.HasIndex("Domain", "MailingId", "Date")
                        .IsUnique();

                    b.ToTable("mailru_postmaster_mailing_daily_metrics", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterMailingSyncStateEntity", b =>
                {
                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<Guid>("MailingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstSendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasData")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastDataFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly?>("LastDateTo")
                        .HasColumnType("date");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("LastSendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnchangedSuccessCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Domain", "MailingId");

                    b.HasIndex("MsgType");

                    b.HasIndex("NextAttemptAt", "CompletedAt");

                    b.ToTable("mailru_postmaster_mailing_sync_states", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterSyncRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("MetricDays")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("TroubleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "StartedAt");

                    b.HasIndex("Domain", "Trigger", "StartedAt");

                    b.ToTable("mailru_postmaster_sync_runs", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterSyncStateEntity", b =>
                {
                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LastDomainDate")
                        .HasColumnType("date");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastMailingSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Domain");

                    b.ToTable("mailru_postmaster_sync_states", (string)null);
                });

            modelBuilder.Entity("Pismolet.Web.Infrastructure.Postmaster.MailruPostmasterTroubleSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "Code")
                        .IsUnique();

                    b.HasIndex("Domain", "IsActive");

                    b.ToTable("mailru_postmaster_trouble_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
